DeathExtraction/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsextraction.urls')),
]

newsextraction/urls.py
from django.urls import path
from . import views


app_name = 'newsextraction'

#url paths for different pages
urlpatterns = [
	path('', views.index, name='home'),
    path('extraction/', views.extraction, name='extraction'),
    path('graph/', views.graph, name='graph'),
    path('search/', views.searchView, name='searchview'),
]

newsextraction/models.py
from django.db import models
from  datetime import date

#all datafields related to the news
class rssdata(models.Model):
	id = models.AutoField(primary_key=True)
	header = models.CharField(blank=True, max_length=200,unique_for_date=True)
	body = models.TextField(blank=False, null=False,unique_for_date=True)
	source = models.CharField(blank=True, max_length=200, null=True)
	death = models.CharField(blank=True, max_length=200, null=True)
	death_no = models.IntegerField(default=0,blank=True, null=True)
	injury = models.CharField(blank=True, max_length=200, null=True)
	injury_no = models.IntegerField(default=0,blank=True, null=True)
	location = models.CharField(blank=True, max_length=200, null=True)
	
	date = models.CharField(default=date.today, blank=True, null=True,max_length=100)
	link = models.CharField(blank=True, max_length=200, null=True)
   
	month = models.CharField(blank=True, max_length=200, null=True)
	year = models.CharField(blank=True, max_length=200, null=True)
	day = models.CharField(blank=True, max_length=200, null=True)


	#vehicle data
	vehicleNo = models.CharField(blank=True, max_length=200, null=True)
	vehicleCode = models.CharField(blank=True, max_length=200, null=True)
	vehicleType = models.CharField(blank=True, max_length=300, null=True) 


	# Timestamps for news object created
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name = 'rssdata' #human readable alias for object
		ordering = ('-date', 'location') #sorting type in list


#override default save method 
	def save(self, *args, **kwargs):
		super(rssdata, self).save(*args, **kwargs)


#Just to identify the object by its header
	def __str__(self):
		return self.header

newsextraction/forms.py
from django import forms
class NameForm(forms.Form):
	"""
	input: news link youu wnat to manually extract
	"""
	news_link = forms.CharField(max_length=500, label='News Link', widget=forms.TextInput(attrs={'class':'form-control', 'id':"newsLinkForm", 'placeholder':'Search'}))
	isSave = forms.BooleanField(required=False)


class SearchForm(forms.Form):
	"""
	form for creating the search form including all the checkboxes to query the search
	"""
	all = forms.BooleanField(widget=forms.CheckboxInput(),initial=True,required=False) # initially search in all fields
	header = forms.BooleanField(widget=forms.CheckboxInput(),required=False)
	body = forms.BooleanField(widget=forms.CheckboxInput(),required=False)
	source = forms.BooleanField(widget=forms.CheckboxInput(),required=False)
	location = forms.BooleanField(widget=forms.CheckboxInput(),required=False)
	death_no = forms.BooleanField(widget=forms.CheckboxInput(),required=False)
	injury_no = forms.BooleanField(widget=forms.CheckboxInput(),required=False)
	date = forms.BooleanField(widget=forms.CheckboxInput(),required=False)
	year = forms.BooleanField(widget=forms.CheckboxInput(),required=False)
	month = forms.BooleanField(widget=forms.CheckboxInput(),required=False)
	day = forms.BooleanField(widget=forms.CheckboxInput(),required=False)

newsextraction/views.py
from newsextraction.modules.utils import initial_check
from newsextraction.modules.utils import *
from newsextraction.modules import newstotext
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, response
from newsextraction.modules.locationTree import LocationInformation
from .forms import NameForm,SearchForm
from .models import *
from .methods import *
from django.db.models import Q #object used to encapsulate a collection of keyword arguments specified as in “Field lookups”.


#runs at start of loading the webpage i.e is homepage, extracts info and load the page
def index(request):
	#initial check stores all the data in the database
	initial_check()
	news_list = rssdata.objects.all().order_by("-date")
	return render(request, 'newsextraction/index.html', {
			'newsList': list(news_list),
			'isHome':True,
		}
	)




def extraction(request):
	linkForm = NameForm()
	if request.method == 'POST':
		linkForm = NameForm(request.POST)
		if(linkForm.is_valid()):
			title, story, link = newstotext.story_extract(linkForm.cleaned_data['news_link'])
			print(title, story, link,sep="\n")
			newsData = extract(link, story, title, "", "", linkForm.cleaned_data['isSave'])	
			return render(request, 'newsextraction/extraction.html', {'isHome':False, 'form':linkForm, 'isData':True, 'news':newsData})
	return render(request, 'newsextraction/extraction.html', {'isHome':False, 'form':linkForm, 'isData':False})


def graph(request):
	alllocationlist, ktmlocationlist, ltplocationlist, bktlocationlist, outsideLocationList, locationCount = getLocations()	
	deathCount = getDeathCountLocation()
	vehicleCount = getVehicleType()
	injuryCount = getInjuryCountLocation()
	print(injuryCount)
	context = {
		'allLocation': alllocationlist,
		'locationCount': locationCount,
		'deathCount': deathCount,
		'vehicleCount': vehicleCount,
		'injuryCount': injuryCount,
		'isHome':False
	}
	print(vehicleCount)
	return render(request, 'newsextraction/visualization.html', context=context) 



def searchView(request):
	"""
	renders the searchform and view the search results
	"""

	checks=[]
	posts=[]
	queries=[]



    #retrieving the inputs from user
	if request.method == 'POST':
		form = SearchForm(data=request.POST)
		search_main =request.POST.get('search_main')
		all = request.POST.get('all')
		header = request.POST.get('header')
		body = request.POST.get('body')
		source = request.POST.get('source')
		death_no = request.POST.get('death_no')
		injury_no = request.POST.get('injury_no')
		location = request.POST.get('location')
		date = request.POST.get('date')
		year = request.POST.get('year')
		month = request.POST.get('month')
		day = request.POST.get('day')
		search_text = request.POST.get('sname')

		
		
		"""
		checking if the search request is from the homepage or searchform
		search_main -> homepage(search in all fields)
		search_text -> searchform(search according to the fields selected in search form)
		"""
		if search_main != None:
			search=search_main

			SearchForm.all=True
			form= SearchForm
			all='on'
			
		else:
			search = search_text



		#checking if the search string can be converted to int value or not
		try: 
			int(search)
			flag = 1

		except ValueError:
			flag = 0

		#querying according to the fields selected

		if (all=='on' and flag ==0):
			queries = rssdata.objects.filter(Q(header__icontains=search)| Q(body__icontains=search)|Q(source__icontains=search)\
				|Q(location__icontains=search)| Q(date__iexact=search)\
					| Q(day__icontains=search) | Q(month__icontains=search))
			for query in queries:
				posts.append(query)

		elif(all == 'on' and flag == 1):
			queries = rssdata.objects.filter(Q(header__icontains=search)| Q(body__icontains=search)|Q(source__icontains=search)\
				|Q(death_no__iexact=int(search))|Q(location__icontains=search)| Q(injury_no__iexact=int(search))| Q(date__iexact=search)\
					|Q(year__iexact=int(search))| Q(day__icontains=search) | Q(month__icontains=search))
			for query in queries:
				posts.append(query)

		else:

			if header=='on':
				queries = rssdata.objects.filter(Q(header__icontains=search))
				for query in queries:
					posts.append(query)

			if body=='on':
				queries = rssdata.objects.filter(Q(body__icontains=search))
				for query in queries:
					posts.append(query)
			if source=='on':
				queries = rssdata.objects.filter(Q(source__icontains=search))
				for query in queries:
					posts.append(query)

			if (death_no=='on' or flag == 1):
				queries = rssdata.objects.filter(Q(death_no__iexact=int(search)))
				for query in queries:
					posts.append(query)
			
			if location=='on':
				queries = rssdata.objects.filter(Q(location__icontains=search))
				for query in queries:
					posts.append(query)

			if (injury_no=='on' and flag == 1):
				queries = rssdata.objects.filter(Q(injury_no__iexact=int(search)))
				for query in queries:
					posts.append(query)
					

			if date=='on':
				queries = rssdata.objects.filter(Q(date__iexact=search))
				for query in queries:
					posts.append(query)

			if (year=='on' and flag == 1):
				queries = rssdata.objects.filter(Q(year__iexact=int(search)))
				for query in queries:
					posts.append(query)

			if day=='on':
				queries = rssdata.objects.filter(Q(day__icontains=search))
				for query in queries:
					posts.append(query)
			if month=='on':
				queries = rssdata.objects.filter(Q(month__icontains=search))
				for query in queries:
					posts.append(query)
		
		posts= list(set(posts))

		context ={}
		context['form']= form
		context['posts']=posts
		context['search'] =search
		context['isHome'] = False

		return render(request, 'newsextraction/search.html', context)
	
	else:
		
		
		print("bbb")
		context ={}
		context['form']= SearchForm()
		context['isHome'] = False
		return render(request, 'newsextraction/search.html', context)

newsextraction/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta name="description" content="" />
	<meta name="author" content="" />
	<title>Disaster Extraction</title>
	<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'customstyle.css' %}" />
	<!-- CSS only -->
	<!-- JavaScript Bundle with Popper -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
		integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
		integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
		crossorigin="anonymous"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" charset="utf-8"></script>
</head>

<body class="sb-nav-fixed">
	<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">

		<!-- Sidebar Toggle-->
		<button class="btn btn-link btn-sm order-1 order-lg-0 me-4 mx-3 me-lg-0" id="sidebarToggle" href="#!"><i
				class="fas fa-bars"></i></button>


		<!-- Navbar Brand-->
		<a class="navbar-brand ps-3" href="{% url 'newsextraction:home' %}">Disaster Extraction</a>

		{% if isHome %}
		<!-- Navbar Search-->
		<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0" method="POST" action="/search/">
		{% csrf_token %}
			<div class="input-group">
				<input class="form-control" type="text" name="search_main" placeholder="Search for..." aria-label="Search for..."
					aria-describedby="btnNavbarSearch" />
				<button class="btn btn-primary" id="btnNavbarSearch" type="submit"><i
						class="fas fa-search" ></i></button>
			</div>
		</form>
		{% endif %}
		<!-- Navbar-->
	</nav>
	<!-- Side Navbar-->
	<div id="layoutSidenav">
		<div id="layoutSidenav_nav">
			<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
				<div class="sb-sidenav-menu">
					<div class="nav">
						<div class="sb-sidenav-menu-heading"> </div>
						<a class="nav-link" href="{% url 'newsextraction:home' %}">
							<div class="sb-nav-link-icon"><i class="fas fa-home"></i></div>
							Home
						</a>
						<a class="nav-link" href="{% url 'newsextraction:graph' %}">
							<div class="sb-nav-link-icon"><i class="fas fa-tv"></i></div>
							Visualization
						</a>
						<a class="nav-link" href="{% url 'newsextraction:extraction' %}">
							<div class="sb-nav-link-icon"><i class="fas fa-download"></i></div>
							Extraction
						</a>
					</div>
				</div>
			</nav>
		</div>
		<div id="layoutSidenav_content">
			<main>
				<div class="container-fluid px-4">
					{% block body %}

					{% endblock %}



				</div>

			</main>
			<footer class="py-4  bg-light mt-5">
				<div class="container-fluid px-4">
					<div class="d-flex align-items-center justify-content-between small">
						<div class="text-muted">Copyright &copy; Casualty Extraction 2021</div>
						<div>
							<a href="#">Privacy Policy</a>
							&middot;
							<a href="#">Terms &amp; Conditions</a>
						</div>
					</div>
				</div>
			</footer>
		</div>
	</div>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
		crossorigin="anonymous"></script>
	<script src="{% static 'js/scripts.js' %}"></script>
	<script src="{% static 'js/extracted_item.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
	<script
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAolA34wmFQsfRRAulAnwdwNWDLOvDdRnw&callback=initmap&libraries=&v=weekly"
		async>
		</script>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js%22%3E"></script>

	{% block script %}

	{% endblock %}



</body>

</html>